site_name: OpenApps

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: false # show the stargazers in the top bar
  pygments_style: # default styles
    light: shadcn-light
    dark: github-dark
  icon: heroicons:rectangle-stack # use the shadcn svg if not defined
  topbar_sections: false # NEW!
  show_datetime: false

site_url: https://facebookresearch.github.io/OpenApps/
nav:
  - Start: index.md
  - Manual Installation: installation.md
  - "Intro to UI Agents": Intro to UI Agents.md
  - Agents: agents.md
  - Tasks: tasks.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.blocks.tab
  - pymdownx.blocks.details
