add_meeting_with_dennis:
  _target_: open_apps.tasks.tasks.AddEventTask
  goal: Go to the Calendar app and add my meeting with Dennis on April 1st of 2026. The title should be 'Dennis-Bob'. Set the description as 'paper reading', omit the URL and set the location to New York City. Make sure to add Dennis as an invitee.
  goal_category: explicit
  event:
    title: Dennis-Bob
    date: 2026-04-01
    description: paper reading
    location: New York City
    url: null
    invitees:
      - Dennis

add_christmas_shopping_event:
  _target_: open_apps.tasks.tasks.AddEventTask
  goal: Make a calendar entry for Christmas shopping on the 14th (2025). The title should read 'Shopping for Christmas gifts'.
  goal_category: explicit
  event:
    title: Shopping for Christmas gifts
    date: 2025-12-14
    description: null
    location: null
    url: null
    invitees: []
